### ISSUE TITLE
State of Project ?

### ISSUE THREAD

**Issue by chris-jh** [fabiodl/peelDecoder#1]
Hello, i am wondering how far you got with this project ?

I have been looking at various forums, to discover if this got completed or not. (eevblog and circuit-board)

Xenogears over on circuit-board, did make some logic code. I converted this into GALasm and i made my own PCB with an adapter for a GAL22v10 and it sort of works.

(i am also waiting to get my account activated on circuit-board)

The MegaCD logo appeared clean, but when i went into the CD menu, there was some glitches on the CD Time Display and i was able to play a Music CD.

But it would not play a game, would get the Sega Licence and stops.

I was discussing this project with other people over on discord (Retro Tinkering) about a year ago, see video link below.

https://cdn.discordapp.com/attachments/828231602693079050/848534100695318548/video0.mov

if you like to join, i will send you a link

**Comment by fabiodl** [comment]
Yes, I'd love to see the discussion. 
I got it working. Here it is. 
[peel5.zip](https://github.com/fabiodl/peelDecoder/files/8804252/peel5.zip)

**Comment by chris-jh** [comment]
@fabiodl here is link to discord, lasts for 7 days

https://discord.gg/4QX2PqmH
